FROM amazonlinux:2

RUN yum install -y amazon-linux-extras && \
    amazon-linux-extras install -y docker && \
    yum install jq -y  &&\
    yum clean all

RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && \
    unzip awscliv2.zip && \
    ./aws/install && \
    rm -rf aws awscliv2.zip && \
    yum clean all

CMD ["bash"]
