FROM amazonlinux:2

RUN yum install -y amazon-linux-extras && \
    amazon-linux-extras install -y docker && \
    yum install -y awscli && \
    yum install jq -y  &&\
    yum clean all

CMD ["bash"]
